version: 2
updates:
- package-ecosystem: npm
  directory: "/api/pb/javascript"
  schedule:
    interval: daily
    time: "03:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 25
  ignore:
  - dependency-name: "@types/google-protobuf"
    versions:
    - 3.15.0
    - 3.15.1
  - dependency-name: google-protobuf
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
