version: "3"
services:
  threads:
    build:
      context: .
    volumes:
      - "${REPO_PATH}/threads:/data/threads"
    environment:
      - THREADS_HOSTADDR
      - THREADS_APIADDR=/ip4/0.0.0.0/tcp/5000
      - THREADS_APIPROXYADDR=/ip4/0.0.0.0/tcp/5050
      - THREADS_CONNLOWWATER
      - THREADS_CONNHIGHWATER
      - THREADS_CONNGRACEPERIOD
      - THREADS_KEEPALIVEINTERVAL
      - THREADS_ENABLENETPUBSUB
      - THREADS_BADGERLOWMEM
      - THREADS_MONGOURI
      - THREADS_MONGODATABASE
      - THREADS_DEBUG=true
    ports:
      - "4006:4006"
      - "4006:4006/udp"
      - "5000:5000"
      - "5050:5050"
