name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  buf:
    name: Buf
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: checkout-master
        run: git checkout master
      - name: checkout
        uses: actions/checkout@v1
      - name: make local
        run: make buf-local
  threadsd:
    name: Threads Daemon
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: make build-threadsd
